name: Terraform Checks

on:
  push:
    branches: [staging, master]
  pull_request:
    branches: [staging, master]

permissions:
  contents: read

jobs:
  terraform-checks:
    name: Terraform Checks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [staging, prod]
    environment: staging

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.5.0

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Terraform Init
      run: terraform init
      working-directory: environments/${{ matrix.environment }}

    - name: Terraform Format Check
      run: terraform fmt -check -recursive
      working-directory: ./

    - name: Terraform Validate
      run: terraform validate
      working-directory: environments/${{ matrix.environment }}

    - name: Terraform Plan
      run: terraform plan -no-color
      working-directory: environments/${{ matrix.environment }}